[project]
name = "attendance-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.42.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "rich>=14.1.0",
    "ruff>=0.12.8",
    "ty>=0.0.1a17",
]
